#.PHONY: one two three four
total: one two three
	@echo "this is the total"
othertotal: one two three four
	@echo "this is the othertotal"
three: one two
	@echo "this is the three"
one:
	@echo "this is the one"
two:
	@echo "this is the two"
four:
	@echo "this is the four"